#!/usr/bin/env bash
# Build-time shim for machines without the GTK4/libadwaita/WebKit *-dev
# packages (which need root to install).
#
# The runtime libraries are present on any Ubuntu GNOME desktop; what the
# -dev packages add is pkg-config metadata and unversioned .so symlinks for
# the linker. This script recreates just those two things under
# target/shim/, so `cargo build` links fine without touching the system.
#
# The resulting binary is normal: it records the usual SONAMEs
# (libgtk-4.so.1 etc.) and runs anywhere those libraries exist.
#
# Preferred alternative, if you have root:
#   sudo apt install libgtk-4-dev libadwaita-1-dev libwebkitgtk-6.0-dev libgraphene-1.0-dev
#
# Usage:  source tools/dev-shim.sh   (then cargo build)
set -u

_shim_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/target/shim"
_libdir="/usr/lib/$(uname -m)-linux-gnu"
mkdir -p "$_shim_root/pkgconfig" "$_shim_root/lib"

# Emit a .pc file only when the real one is absent.
_shim_pc() { # name version libs [requires]
  local name="$1" version="$2" libs="$3" requires="${4:-}"
  pkg-config --exists "$name" 2>/dev/null && return 0
  cat > "$_shim_root/pkgconfig/$name.pc" <<EOF
prefix=/usr
libdir=$_shim_root/lib
includedir=/usr/include

Name: $name
Description: shim for $name (generated by tools/dev-shim.sh)
Version: $version
Requires: $requires
Libs: -L\${libdir} $libs
Cflags:
EOF
}

# Unversioned symlink so the linker can resolve -lfoo.
_shim_lib() { # soname-stem  actual-file
  local stem="$1" actual="$2"
  [ -e "$_libdir/lib$stem.so" ] && return 0
  [ -e "$actual" ] || { echo "dev-shim: missing $actual" >&2; return 1; }
  ln -sf "$actual" "$_shim_root/lib/lib$stem.so"
}

# Detect installed versions from the SONAMEs actually present.
_ver_of() { # glob -> best version string, or fallback
  local f
  f=$(ls -1 "$1" 2>/dev/null | sort -V | tail -1)
  [ -n "$f" ] && echo "${f##*.so.}" || echo ""
}

# --- graphene ---------------------------------------------------------
_shim_lib graphene-1.0 "$(ls -1 $_libdir/libgraphene-1.0.so.0* 2>/dev/null | head -1)"
_shim_pc graphene-1.0 "1.10.8" "-lgraphene-1.0" "glib-2.0 gobject-2.0"
_shim_pc graphene-gobject-1.0 "1.10.8" "-lgraphene-1.0" "glib-2.0 gobject-2.0"

# --- gtk4 -------------------------------------------------------------
_shim_lib gtk-4 "$(ls -1 $_libdir/libgtk-4.so.1* 2>/dev/null | head -1)"
_gtk_ver=$(pkg-config --modversion gtk4 2>/dev/null || echo "")
if [ -z "$_gtk_ver" ]; then
  _gtk_ver=$(ls -1 $_libdir/libgtk-4.so.1.* 2>/dev/null | sed 's/.*so\.1\.//' | sort -V | tail -1)
  # libgtk-4.so.1.1400.5  ->  4.14.5
  _gtk_ver="4.$(( ${_gtk_ver%%.*} / 100 )).${_gtk_ver##*.}"
fi
_shim_pc gtk4 "$_gtk_ver" "-lgtk-4" \
  "glib-2.0 gobject-2.0 gio-2.0 cairo cairo-gobject pango pangocairo gdk-pixbuf-2.0 graphene-gobject-1.0"

# --- libadwaita -------------------------------------------------------
_shim_lib adwaita-1 "$(ls -1 $_libdir/libadwaita-1.so.0* 2>/dev/null | head -1)"
_adw_ver=$(dpkg-query -W -f='${Version}' libadwaita-1-0 2>/dev/null | sed 's/[-+].*//' || true)
_shim_pc libadwaita-1 "${_adw_ver:-1.5.0}" "-ladwaita-1" "gtk4 gio-2.0"

# --- webkitgtk 6.0 ----------------------------------------------------
_shim_lib webkitgtk-6.0 "$(ls -1 $_libdir/libwebkitgtk-6.0.so.4* 2>/dev/null | head -1)"
_shim_lib javascriptcoregtk-6.0 "$(ls -1 $_libdir/libjavascriptcoregtk-6.0.so.1* 2>/dev/null | head -1)"
_wk_ver=$(dpkg-query -W -f='${Version}' libwebkitgtk-6.0-4 2>/dev/null | sed 's/[-+].*//' || true)
_shim_pc javascriptcoregtk-6.0 "${_wk_ver:-2.44.0}" "-ljavascriptcoregtk-6.0" "glib-2.0 gobject-2.0"

# libsoup is a transitive dep of webkit; shim it too when soup3-dev is absent.
_shim_lib soup-3.0 "$(ls -1 $_libdir/libsoup-3.0.so.0* 2>/dev/null | head -1)"
_soup_ver=$(dpkg-query -W -f='${Version}' libsoup-3.0-0 2>/dev/null | sed 's/[-+].*//' || true)
_shim_pc libsoup-3.0 "${_soup_ver:-3.4.4}" "-lsoup-3.0" "glib-2.0 gobject-2.0 gio-2.0"

_shim_pc webkitgtk-6.0 "${_wk_ver:-2.44.0}" "-lwebkitgtk-6.0" "gtk4 javascriptcoregtk-6.0 gio-2.0 libsoup-3.0"

export PKG_CONFIG_PATH="$_shim_root/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
export RUSTFLAGS="-L $_shim_root/lib${RUSTFLAGS:+ $RUSTFLAGS}"

echo "dev-shim: PKG_CONFIG_PATH -> $_shim_root/pkgconfig"
echo "dev-shim: gtk4 $(pkg-config --modversion gtk4 2>/dev/null), libadwaita-1 $(pkg-config --modversion libadwaita-1 2>/dev/null), webkitgtk-6.0 $(pkg-config --modversion webkitgtk-6.0 2>/dev/null)"
